# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import pprint as pp

# Import API key
from api_keys import g_key

# Input File (CSV)
weather_data_path = "output_data/weather_data.csv"

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv(weather_data_path).reset_index(drop=True)
display(weather_data)

,Unnamed: 0,City_ID,City,Cloudiness,Country,Date,Date Converted,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,3883457,Lebu,85,CL,1666723213,2022-10-25 18:40:13,77,-37.6167,-73.6500,58.46,13.62
1,1,2122090,Pevek,12,RU,1666723215,2022-10-25 18:40:15,91,69.7008,170.3133,0.32,7.38
2,2,3369157,Cape Town,20,ZA,1666723014,2022-10-25 18:36:54,86,-33.9258,18.4232,64.11,18.41
3,3,3423146,Ilulissat,75,GL,1666723216,2022-10-25 18:40:16,93,69.2167,-51.1000,28.42,3.44
4,4,964420,Port Elizabeth,20,ZA,1666723024,2022-10-25 18:37:04,81,-33.9180,25.5701,64.09,12.66
...,...,...,...,...,...,...,...,...,...,...,...,...
567,567,1252795,Yanam,0,IN,1666723586,2022-10-25 18:46:26,81,16.7333,82.2167,73.96,0.58
568,568,1636544,Manado,40,ID,1666723587,2022-10-25 18:46:27,100,1.4870,124.8455,75.97,2.30
569,569,5959326,Gananoque,92,CA,1666723588,2022-10-25 18:46:28,74,44.3334,-76.1661,75.47,11.18
570,570,687191,Zhelyabovka,73,UA,1666723589,2022-10-25 18:46:29,78,45.3988,34.7578,55.08,6.91
571,571,5478673,Meadow Lake,0,US,1666723589,2022-10-25 18:46:29,30,34.8014,-106.5436,56.70,6.82

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)

In [4]:
# Create a list containing coordinates
coordinates = list(zip(weather_data["Lat"],weather_data["Lng"]))
print(coordinates)

[(-37.6167, -73.65), (69.7008, 170.3133), (-33.9258, 18.4232), (69.2167, -51.1), (-33.918, 25.5701), (5.0268, 118.327), (55.7435, -97.8558), (-54.8, -68.3), (-21.2, -175.2), (71.9667, 102.5), (-23.1203, -134.9692), (64.2457, 12.3778), (-24.8667, 113.6333), (72.7868, -56.1549), (69.4541, -133.0374), (-22.45, 18.9667), (42.097, -79.2353), (-8.1881, 15.375), (-9.8, -139.0333), (59.7035, 30.7861), (65.0083, 53.9113), (-24.7911, -50.0119), (36.7833, 140.75), (3.0707, 172.7902), (40.4272, 71.7189), (67.45, 153.6833), (-16.1667, 49.7667), (-45.5752, -72.0662), (71.2906, -156.7887), (-33.5906, 26.891), (60.7522, -137.5108), (51.0333, -4.2167), (-21.2078, -159.775), (19.7297, -155.09), (-25.4, -70.4833), (58.4786, 41.53), (50.8552, 0.5729), (70.6333, 147.9167), (64.8989, 45.7622), (-35.1667, 173.1667), (58.1908, 40.1717), (50.5667, 123.7167), (66.4167, 112.4), (-42.8794, 147.3294), (7.1712, -75.764), (-20.3428, 57.7575), (65.75, 150.85), (-34.6833, 150.8667), (-21.6403, -41.0511), (-53.15, -70.9167), (-8.145, 159.5921), (65.4167, -52.9), (42.6001, -73.9662), (34.5667, 76.1), (32.6667, -17.1), (-6.1349, 12.3689), (-33.0117, 17.9442), (-34.5322, 20.0403), (55.1001, -105.2842), (69.4865, 88.3972), (57.0531, -135.33), (64.1835, -51.7216), (42.2506, -75.833), (-33.65, 115.3333), (15.7333, 79.2833), (-46.6, 168.3333), (-20.7333, 139.5), (-46.1927, 168.8643), (-31.95, 141.4333), (65.3667, 64.6667), (41.7597, 86.1469), (33.3703, -112.5838), (-10.4544, 161.9205), (-0.9131, 122.8766), (62.456, -114.3525), (11.6667, 92.75), (60.0625, 71.4789), (54.9901, 62.5442), (14.9709, 8.8879), (62.2266, -6.589), (-18.0607, 13.84), (-2.5744, 150.7967), (13.2167, -59.5167), (-20.4081, 57.7), (65.7, 82.4667), (42.0551, 59.3788), (61.9875, 5.1352), (-22.9661, -42.0278), (34.6667, 138.95), (62.6012, 29.7632), (-16.9167, 145.7667), (-2.6741, 141.3028), (3.7833, 72.9667), (69.3, 139.9), (40.5982, -124.1573), (-19.8, -174.35), (41.3712, -73.414), (14.35, 121.0167), (-34.4187, 19.2345), (-33.0153, 27.9116), (-28.783, 32.0377), (-19.55, 169.2667), (30.7554, 20.2263), (35.1333, 140.3), (-41.4122, 175.5153), (-10.6167, 150.6667), (3.65, 18.6333), (47.0529, -122.2943), (14.4833, 79.9833), (-3.4833, 23.4333), (36.4989, 111.7047), (47.5999, -53.2648), (37.1041, -113.5841), (31.6682, 20.2521), (70.9821, 25.9704), (10.9995, 122.6711), (12.2175, 4.3792), (44.0169, -107.9554), (-38.0023, -57.5575), (14.8961, -24.4956), (-29.9533, -71.3436), (-18.4733, -47.2003), (49.9168, -109.4848), (-0.7393, -90.3518), (-28.7667, 114.6), (57.79, -152.4072), (77.484, -69.3632), (22.0752, -159.319), (20.931, -17.0347), (24.6877, 46.7219), (-21.3585, 55.7679), (61.9449, 76.6625), (-19.0595, -169.9187), (44.9444, -93.0933), (-8.9266, 125.4092), (-20.3167, 118.5667), (71.9167, 114.0833), (63.05, 179.3167), (19.9333, -105.25), (70.6634, 23.6821), (43.3236, 145.575), (8.0086, -62.3989), (4.1363, 96.1285), (50.6789, 156.125), (-42.7826, 147.0587), (34.6391, -120.4579), (50.2334, -63.5986), (27.9994, 120.6668), (-16.7, -151.0167), (-11.0964, -77.6139), (25.5198, 90.2201), (45.8456, 41.5186), (11.2833, -15.8333), (38.5917, 31.0286), (-8.4667, 140.3333), (-10.7417, -40.3608), (64.2539, -15.2082), (73.5069, 80.5464), (19.2833, -81.25), (7.7669, -72.225), (49.7579, 0.3746), (-20.7833, 117.1333), (71.6872, 128.8694), (-33.6971, -53.4616), (21.3469, -158.0858), (-3.0254, -60.1803), (18.2271, -66.3917), (26.8865, 88.0718), (37.6803, 112.7319), (-6.9811, -34.8339), (-26.6481, 15.1594), (50.2001, -66.3821), (-20.2333, 164.0167), (10.5669, 72.642), (-20.5167, 57.5167), (68.0531, 39.5131), (-15.1961, 12.1522), (41.8069, 126.9078), (57.6409, 18.296), (4.9333, -52.3333), (28.6585, -17.9182), (37.4193, 31.8453), (-35.3333, -72.4167), (-34.0033, 24.7314), (50.1001, -91.917), (39.1834, -84.5333), (-17.4667, 16.3333), (-8.345, 113.6058), (29.3669, -99.767), (66.0449, -17.3389), (-39.0333, -67.5833), (18.1, 76.7667), (5.3833, -52.95), (70.9963, 24.6622), (47.6666, -52.7314), (34.6087, -98.3903), (51.9, -1.1536), (47.6166, -117.3677), (63.7506, -68.5145), (20.8624, 92.3058), (51.226, -58.6502), (9.4942, 50.8122), (11.6636, -1.0731), (56.45, 138.1667), (-34.5833, 150.8552), (-30.1811, -50.2056), (50.6996, -127.4199), (17.4924, 44.1277), (38.7173, 69.7088), (10.1815, 119.236), (38.421, -121.4238), (66.0, 111.5), (45.5234, -122.6762), (49.6333, 117.3167), (38.8403, -97.6114), (7.9986, 124.2928), (42.6667, -83.3999), (18.7333, -103.6833), (67.667, 12.6934), (18.3851, 42.4509), (54.7183, 135.315), (-10.1667, 123.5833), (-38.2667, 141.9667), (-46.1333, 167.6833), (38.7333, -27.0667), (41.5823, -85.8344), (-25.2406, 130.9889), (-23.865, 35.3833), (55.2834, -114.769), (38.5167, -28.7), (32.2994, -9.2372), (-43.5333, 172.6333), (-17.5333, -149.3333), (-46.2817, 169.8464), (4.9247, 6.2642), (-45.8742, 170.5036), (-20.3297, -40.2925), (65.5833, -171.0), (2.0371, 45.3438), (-51.6226, -69.2181), (4.2891, -74.8982), (38.065, 30.1656), (-20.2078, 57.7625), (29.3627, -100.8968), (-6.6447, -51.995), (78.2186, 15.6401), (41.3, -96.167), (45.6834, 5.9224), (20.4487, 121.9702), (17.4897, 104.1006), (13.9216, 44.1467), (8.4833, 78.1167), (65.282, -126.8329), (22.9167, 96.5), (50.7214, 136.6319), (36.175, -115.1372), (-21.3667, 55.6167), (-5.6667, 132.75), (-33.8667, 121.9), (17.4189, 121.4443), (22.2855, 114.1577), (39.05, -27.9833), (66.3167, -179.1667), (-3.0167, 16.9), (64.3833, -173.3), (35.8786, 119.9753), (31.2156, 29.9553), (53.2115, 60.6069), (-5.5569, -80.8222), (-0.9, -89.6), (32.6941, 47.2679), (19.75, 10.25), (4.95, 23.9167), (-13.2, 49.05), (-6.2167, 155.6333), (7.3706, 7.6253), (5.3473, 115.7455), (32.3256, 50.8644), (39.1672, 8.5222), (70.4692, -68.5914), (-0.6, 73.0833), (20.8947, -156.47), (57.3064, 88.1667), (41.6096, -4.7969), (37.6138, -122.4869), (-30.0392, -52.8939), (29.8, 72.8667), (61.95, 159.2333), (27.0377, 14.4283), (5.9667, 80.4167), (50.3557, 44.1168), (5.1033, 73.0708), (1.1667, 108.9667), (-17.7333, -149.15), (70.3705, 31.1107), (49.4992, -98.0016), (-34.5703, -59.105), (45.7167, 25.6833), (54.6961, 20.2361), (-32.5, 137.7667), (30.95, 117.7833), (-2.1667, 16.2333), (-31.6333, -60.7), (-0.1303, -67.0892), (43.7501, -81.7165), (64.8569, -147.8028), (53.4106, -2.9779), (63.8424, -22.4338), (63.2909, 18.7153), (39.447, -86.1758), (38.5106, -1.701), (1.5995, 11.5793), (-17.6203, 27.3414), (55.2689, 66.4947), (57.4467, 97.3217), (3.4836, 103.3996), (46.6166, 10.7002), (-23.7, 133.8833), (4.8845, -1.7554), (-21.15, 149.2), (28.9167, 80.3333), (36.6177, -121.9166), (26.5851, 101.7128), (56.2501, -117.286), (35.3029, 37.1841), (68.75, 161.3), (-34.2, 142.15), (-8.7676, 160.7034), (-7.7958, -35.5872), (-29.6641, 22.7474), (17.1561, -89.0714), (7.1333, 40.7), (6.6451, -4.7048), (12.8347, -4.9244), (65.6145, -37.6368), (29.2947, 117.2079), (56.9464, 65.4278), (23.7667, -98.2167), (31.7167, -116.5667), (60.623, 6.4229), (58.3131, 82.9089), (61.2767, 108.0108), (25.0833, -108.05), (63.4453, 120.3167), (68.5646, 14.9108), (-23.3428, -57.0597), (41.5775, 21.9428), (1.3292, 172.9752), (68.3065, -53.4641), (59.3736, 41.0305), (-37.8333, 140.7667), (60.9167, -46.05), (66.5, 25.7167), (-17.4961, -149.8729), (27.9769, -114.0611), (-6.9081, -79.8642), (-26.6322, -48.6847), (60.1432, -45.2371), (-4.5772, -81.2719), (42.8, 93.45), (29.1614, 16.139), (-13.8833, 167.55), (-2.65, 10.0), (-45.4167, 167.7167), (14.0833, 98.2), (46.3167, 22.5167), (55.3422, -131.6461), (6.6167, -1.2167), (41.25, 36.3333), (50.3, 87.7333), (33.4537, 50.2884), (68.2191, -135.0107), (-20.2333, 47.3833), (52.4153, 60.3411), (15.7432, -96.4661), (37.5683, 126.9778), (69.3833, 178.4167), (-2.0226, 147.2712), (29.85, 80.5333), (-8.0089, -34.8553), (37.3394, -121.895), (46.4631, 10.347), (-9.8756, -56.0861), (53.5739, 142.9478), (22.6783, -3.9836), (9.5167, -79.0333), (65.9667, 78.3667), (14.298, 44.3779), (50.5881, 107.6022), (23.1667, -97.95), (-17.8814, -51.7144), (45.6169, -61.3485), (-13.3433, -44.6367), (22.8909, -109.9124), (5.4112, 100.3354), (19.8, 85.85), (40.1629, -8.3327), (-26.5333, 29.9833), (-12.5763, 13.4055), (-18.1853, 31.5519), (54.3, 110.3), (65.8522, 44.24), (55.2169, 62.0634), (9.6139, 6.5569), (8.9333, 8.6), (27.4327, 120.6062), (60.907, 26.6244), (30.1165, 55.1186), (48.5501, -71.3324), (20.8667, -90.4), (-20.0819, -49.9142), (-35.1, 173.7833), (44.0361, 39.1489), (30.634, 117.8517), (-20.5667, 164.2833), (35.8881, -106.307), (-41.5333, 146.6667), (7.5264, -12.505), (29.05, -109.2333), (24.9, -76.2), (30.2297, 115.4335), (-22.9575, 14.5053), (48.5722, 83.6542), (59.3833, 143.3), (66.8333, 70.8333), (42.9019, 133.9064), (-20.1, 146.2667), (1.3038, 124.9112), (35.0, 132.2167), (33.8464, -118.0467), (52.05, -9.5167), (42.1584, -72.3287), (-24.7117, 33.8828), (-34.4833, -54.3333), (-17.0392, -39.5311), (62.8487, 34.8262), (44.6453, -63.5724), (-22.6667, 167.4833), (26.0333, 80.6), (36.3703, 30.2869), (64.5011, -165.4064), (32.834, -109.7076), (54.3161, -130.3201), (-0.2167, 20.8667), (46.5389, 138.3297), (-1.195, -46.02), (2.6708, 72.8944), (51.1537, 37.8879), (27.2025, 60.6848), (-29.0806, -53.8358), (30.4833, -115.95), (-7.4167, 30.6), (-7.6087, 15.0613), (52.6844, 62.5794), (45.7625, 106.2708), (52.1451, 25.5365), (32.2163, -80.7526), (36.3209, 41.8754), (-15.7667, 128.7333), (52.6083, 1.7305), (53.015, 13.9992), (54.5163, -128.6035), (32.7941, -79.8626), (29.2195, 119.477), (18.4167, -64.6167), (-2.5364, -57.76), (60.7167, -46.0333), (5.9749, 116.0724), (-1.6822, -50.4803), (-34.6515, -59.4307), (41.1415, -73.3579), (-22.7094, -52.6169), (47.4334, -72.7824), (39.4184, -92.4382), (-9.4061, -38.2147), (10.05, 78.3333), (1.55, 110.3333), (-38.3833, 142.4833), (40.4163, -120.653), (64.75, 177.4833), (-6.3424, 106.1045), (29.6195, 51.6541), (37.7167, -25.4333), (-16.4833, -151.75), (-34.6177, -68.3301), (40.8021, -124.1637), (-20.2833, 44.2833), (20.7, -105.2), (-0.8917, 119.8707), (-45.8667, -67.5), (7.3179, 8.9951), (-0.9492, 100.3543), (-22.4667, -68.9333), (-8.4192, 20.7447), (35.244, 60.6225), (-11.3847, 43.2844), (-11.8069, -39.3856), (14.3188, 2.0866), (13.2954, 19.6966), (-38.3333, 143.5833), (-16.0335, 34.8009), (-18.65, -173.9833), (29.0331, 21.5482), (6.7989, 81.4808), (43.4065, -124.2243), (1.7427, 98.7792), (20.5169, -13.0499), (51.3813, 1.3862), (29.85, 74.95), (13.5828, -2.4216), (26.1842, 127.7558), (45.0205, -93.218), (6.8837, 116.8477), (64.0019, 44.4451), (5.5577, 95.3222), (66.1451, -65.7125), (8.25, 34.5833), (61.67, 96.37), (7.9803, 49.8164), (55.1667, 124.7167), (46.7379, -119.9028), (62.5903, 40.6066), (-15.6178, -46.4233), (43.2841, 43.6559), (64.8378, -147.7164), (-25.1667, 45.05), (-5.1989, -35.4608), (40.2833, 97.2), (29.5667, -104.4167), (36.3868, 4.3989), (60.4667, 166.1), (10.2849, 22.7882), (50.0229, 29.0202), (28.419, 30.7792), (20.9, 70.3667), (59.2667, 32.85), (61.9247, 63.0231), (-3.7481, -73.2472), (49.6775, 12.1567), (61.8099, 36.5345), (36.2171, 136.1519), (17.0151, 54.0924), (-9.3333, 34.7667), (41.8666, -103.6672), (21.4447, -157.8378), (-32.035, -52.0986), (10.3667, -84.6167), (53.6039, 91.3903), (2.8197, -60.6733), (28.2719, 83.5898), (25.2867, 51.5333), (41.1231, 80.2644), (58.8053, -122.7002), (13.35, -15.75), (46.4333, 26.4), (-35.35, 150.4667), (49.2361, 135.1742), (-33.0393, -71.6273), (-21.6924, 165.677), (-13.8745, -171.5986), (53.1333, 132.9), (-12.7761, 15.7392), (-34.7333, 135.8667), (-35.9333, 173.8833), (-12.0432, -77.0282), (47.2456, 47.0281), (-28.615, -49.0256), (16.7333, 82.2167), (1.487, 124.8455), (44.3334, -76.1661), (45.3988, 34.7578), (34.8014, -106.5436)]

In [5]:
# Customize the size of the figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

In [6]:
# Assign the marker layer to a variable
#markers = gmaps.marker_layer(coordinates)
heatmap = gmaps.heatmap_layer(coordinates, weights=weather_data["Humidity"])

# Add the layer to the map
#fig.add_layer(markers)
fig.add_layer(heatmap)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [42]:
vacation_places = weather_data.loc[(weather_data["Max Temp"]>=70)&(weather_data["Max Temp"]<80)&(weather_data["Wind Speed"]<10)&(weather_data["Cloudiness"]==0)&(weather_data["Humidity"]>30)&(weather_data["Humidity"]<50)].reset_index(drop=True)

display(vacation_places)

,Unnamed: 0,City_ID,City,Cloudiness,Country,Date,Date Converted,Humidity,Lat,Lng,Max Temp,Wind Speed
0,16,5122534,Jamestown,0,US,1666723226,2022-10-25 18:40:26,43,42.0970,-79.2353,76.59,9.22
1,161,2062276,Roebourne,0,AU,1666723050,2022-10-25 18:37:30,41,-20.7833,117.1333,73.83,8.95
2,285,3468436,Cachoeira do Sul,0,BR,1666723118,2022-10-25 18:38:38,43,-30.0392,-52.8939,79.70,9.15
3,354,4021858,Guerrero Negro,0,MX,1666723439,2022-10-25 18:43:59,31,27.9769,-114.0611,75.97,3.11
4,360,2209055,Waddān,0,LY,1666723446,2022-10-25 18:44:06,34,29.1614,16.1390,73.06,8.99
5,418,3988265,Sahuaripa,0,MX,1666723484,2022-10-25 18:44:44,34,29.0500,-109.2333,77.70,3.33
6,429,5364022,La Palma,0,US,1666723488,2022-10-25 18:44:48,34,33.8464,-118.0467,79.77,4.61
7,438,1275572,Bindki,0,IN,1666723494,2022-10-25 18:44:54,42,26.0333,80.6000,71.37,0.96
8,449,3445939,Tupanciretã,0,BR,1666723406,2022-10-25 18:43:26,43,-29.0806,-53.8358,79.43,8.63
9,502,86049,Jalu,0,LY,1666723538,2022-10-25 18:45:38,39,29.0331,21.5482,74.19,7.14

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [43]:
hotel_df = vacation_places.copy().reset_index(drop=True)
hotel_df["Hotel Name"] = ""

display(hotel_df)

,Unnamed: 0,City_ID,City,Cloudiness,Country,Date,Date Converted,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,16,5122534,Jamestown,0,US,1666723226,2022-10-25 18:40:26,43,42.0970,-79.2353,76.59,9.22,
1,161,2062276,Roebourne,0,AU,1666723050,2022-10-25 18:37:30,41,-20.7833,117.1333,73.83,8.95,
2,285,3468436,Cachoeira do Sul,0,BR,1666723118,2022-10-25 18:38:38,43,-30.0392,-52.8939,79.70,9.15,
3,354,4021858,Guerrero Negro,0,MX,1666723439,2022-10-25 18:43:59,31,27.9769,-114.0611,75.97,3.11,
4,360,2209055,Waddān,0,LY,1666723446,2022-10-25 18:44:06,34,29.1614,16.1390,73.06,8.99,
5,418,3988265,Sahuaripa,0,MX,1666723484,2022-10-25 18:44:44,34,29.0500,-109.2333,77.70,3.33,
6,429,5364022,La Palma,0,US,1666723488,2022-10-25 18:44:48,34,33.8464,-118.0467,79.77,4.61,
7,438,1275572,Bindki,0,IN,1666723494,2022-10-25 18:44:54,42,26.0333,80.6000,71.37,0.96,
8,449,3445939,Tupanciretã,0,BR,1666723406,2022-10-25 18:43:26,43,-29.0806,-53.8358,79.43,8.63,
9,502,86049,Jalu,0,LY,1666723538,2022-10-25 18:45:38,39,29.0331,21.5482,74.19,7.14,

In [44]:
# find the closest hotel within 5000 m to coordinates


# Create a set of lat and lng combinations from the previous dataframe
lats = hotel_df["Lat"].values
lngs = hotel_df["Lng"].values


base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for each, city in hotel_df.iterrows():

    params = {
    "keyword": "Hotel",
    "location": f'{lats[each]}, {lngs[each]}',
    "radius": "5000",
    "key": g_key,
    }
    
    # assemble url and make API request
    print(f"Retrieving Results for Index {each}: {hotel_df['City'].loc[hotel_df.index[each]]}")
    response = requests.get(base_url, params=params).json()
         
    # extract results
    results = response['results']

    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[each, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
    
    print("------------")

Retrieving Results for Index 0: Jamestown
Closest hotel is Chautauqua Harbor Hotel.
------------
Retrieving Results for Index 1: Roebourne
Closest hotel is Latitude20 Roebourne Village.
------------
Retrieving Results for Index 2: Cachoeira do Sul
Closest hotel is HOTEL JACUÍ.
------------
Retrieving Results for Index 3: Guerrero Negro
Closest hotel is The Halfway Inn.
------------
Retrieving Results for Index 4: Waddān
Closest hotel is hotel bashir tajouri.
------------
Retrieving Results for Index 5: Sahuaripa
Closest hotel is Hotel y Restaurante Alameda.
------------
Retrieving Results for Index 6: La Palma
Closest hotel is Courtyard by Marriott Anaheim Buena Park.
------------
Retrieving Results for Index 7: Bindki
Closest hotel is SPOT ON 49043 Hotel Silver Palace.
------------
Retrieving Results for Index 8: Tupanciretã
Closest hotel is Hotel Cassino.
------------
Retrieving Results for Index 9: Jalu
Closest hotel is إستراحة صلاح الصادق.
------------

In [45]:
# Remove all the cities where a hotel was not found

hotel_df_NaN = hotel_df.copy()
hotel_df_NaN['Hotel Name'].replace('', np.nan, inplace=True)

hotel_df_clean = hotel_df_NaN.dropna().reset_index(drop=True)

display(hotel_df_clean)

,Unnamed: 0,City_ID,City,Cloudiness,Country,Date,Date Converted,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,16,5122534,Jamestown,0,US,1666723226,2022-10-25 18:40:26,43,42.0970,-79.2353,76.59,9.22,Chautauqua Harbor Hotel
1,161,2062276,Roebourne,0,AU,1666723050,2022-10-25 18:37:30,41,-20.7833,117.1333,73.83,8.95,Latitude20 Roebourne Village
2,285,3468436,Cachoeira do Sul,0,BR,1666723118,2022-10-25 18:38:38,43,-30.0392,-52.8939,79.70,9.15,HOTEL JACUÍ
3,354,4021858,Guerrero Negro,0,MX,1666723439,2022-10-25 18:43:59,31,27.9769,-114.0611,75.97,3.11,The Halfway Inn
4,360,2209055,Waddān,0,LY,1666723446,2022-10-25 18:44:06,34,29.1614,16.1390,73.06,8.99,hotel bashir tajouri
5,418,3988265,Sahuaripa,0,MX,1666723484,2022-10-25 18:44:44,34,29.0500,-109.2333,77.70,3.33,Hotel y Restaurante Alameda
6,429,5364022,La Palma,0,US,1666723488,2022-10-25 18:44:48,34,33.8464,-118.0467,79.77,4.61,Courtyard by Marriott Anaheim Buena Park
7,438,1275572,Bindki,0,IN,1666723494,2022-10-25 18:44:54,42,26.0333,80.6000,71.37,0.96,SPOT ON 49043 Hotel Silver Palace
8,449,3445939,Tupanciretã,0,BR,1666723406,2022-10-25 18:43:26,43,-29.0806,-53.8358,79.43,8.63,Hotel Cassino
9,502,86049,Jalu,0,LY,1666723538,2022-10-25 18:45:38,39,29.0331,21.5482,74.19,7.14,إستراحة صلاح الصادق

In [48]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df_clean.iterrows()]
locations = hotel_df_clean[["Lat", "Lng"]]

In [49]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations)
symbol_layer = gmaps.symbol_layer(locations, info_box_content=hotel_info)

# Add the layer to the map
fig = gmaps.figure()
fig.add_layer(markers)
fig.add_layer(heatmap)
fig.add_layer(symbol_layer)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))